import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import argparse
import sys
from src.experiment_handler import ExperimentHandler
from tensorflow.keras import mixed_precision

 # This component defines an entry point for the whole system. Both for training and inference.

def main():
    # Experiments
    experiments = [
    #    {'name': 'ModelA', 'arch': 'mlp', 'red': None},
        {'name': 'ModelB', 'arch': 'cnn', 'red': 'gap2d'},
        {'name': 'ModelC', 'arch': 'cnn', 'red': 'gmp2d'},
        {'name': 'ModelD', 'arch': 'cnn', 'red': 'flatten'},
    ]

    # Args
    parser = argparse.ArgumentParser(description="Industry 4.0 Cast Defect Detector - Training and Inference")
    parser.add_argument(
        '--mode',
        choices=['train', 'predict', 'evaluate', 'original_evaluation'],
        default='train',
        help='Mode: train or predict'
    )
    parser.add_argument(
        '--batch_size',
        type=int,
        default=16,
        help='Batch size for training mode.'
    )
    parser.add_argument(
        '--lr',
        type=float,
        default=0.01,
        help='Learning rate for training mode.'
    )
    parser.add_argument(
        '--epochs',
        type=int,
        default=20,
        help='No. of epochs for training mode.'
    )
    parser.add_argument(
        '--model_path',
        type=str,
        default='models/ModelC.keras', # set the best model as the default one
        help="Path of the chosen model for inference. Only for predict mode."
    )
    parser.add_argument(
        '--image_path',
        type=str,
        help="Path of the image to predict. Only for predict mode."
    )
    parser.add_argument(
        '--save_path',
        type=str,
        help="Path to save confusion matrices generated by evaluations."
    )
    parser.add_argument(
        '--folder_path',
        type=str,
        help="Path to the folder to predict."
    )
    parser.add_argument(
        "--mp",
        action="store_true",
        help="Activate the Mixed Precision. Only for training mode.")
    args = parser.parse_args()

    config = {
        'batch_size': args.batch_size,
        'lr': args.lr,
        'img_size': (300,300),
        'epochs': args.epochs
    }

    handler = ExperimentHandler(config)


    if args.mode == "train":
        print(f"Starting training for {len(experiments)} experiments.")
        handler.run_experiments(experiments)
        if args.mp:
            policy = mixed_precision.Policy('mixed_float16')
            mixed_precision.set_global_policy(policy)
            print("Training with mixed precision.")

    elif args.mode == 'predict':
        if not args.model_path:
            parser.error("Model_path is required for predict mode.")
        if args.folder_path:
            handler.run_folder_inference(args.model_path, args.folder_path)
        elif args.image_path:
            handler.run_inference(args.model_path, args.image_path)
        else:
            parser.error("You must provide either --image_path or --folder_path for predict mode.")

    elif args.mode == 'evaluate':
        if not args.model_path:
            parser.error(f"Model_path is required.")
        handler.run_evaluation(args.model_path)

    elif args.mode == 'original_evaluation':
        handler.run_original_evaluation(args.model_path)

if __name__ == "__main__":
    try: main()
    except Exception as e:
        print(e)
        sys.exit(1)